In [244]:
# Relevant imports 
import pandas as pd
import numpy as np
import torch
import binance
from collections import namedtuple
from utils.config import API_SECRET,API_KEY
from binance import Client
from utils.get_data_binance import getbinance
from utils.get_data_bitstamp import getbitstamp
from utils.get_data_full import get_data
import requests
from torch.utils.data import Dataset, DataLoader
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
from torch import optim

# Building a dataset

## Reading data from common exchanges

In [2]:
Coinlist = ['BTC', 'ADA', 'DOGE', 'ETH', 'LINK', 'LTC', 'XRP']

In [3]:
for a in Coinlist :
    df = get_data(ticker = a)
    print(len(df.index), a)

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

16364 BTC

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')
indexed on binance

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

14911 ADA

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')
indexed on binance

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

12245 DOGE

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

16364 ETH

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')
indexed on binance

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

13266 LINK

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

16364 LTC

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_bitstamp.py:67: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start, end, freq = "4000H", inclusive="both")

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume'], dtype='object')
16364 XRP

/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA = [SMA[0]]
/Users/ochaff/Documents/cardo_local/RL_project/utils/get_data_full.py:47: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  EMA.append((price[i+1]-EMA[i])*mult+EMA[i])

In [4]:
for a in Coinlist : 
    df = pd.read_parquet(f'./data/{a}_4hours.parquet')
    print(len(df.index), a)

16364 BTC
14911 ADA
12245 DOGE
16364 ETH
13266 LINK
16364 LTC
16364 XRP

In [64]:
dfBTC = pd.read_parquet('./data/BTC_4hours.parquet')
df_all =dfBTC[['high','low','close']]
for a in Coinlist[1:] :
    df = pd.read_parquet(f'./data/{a}_4hours.parquet')
    df =df[['high','low','close']]
    df_all = df_all.join(df, how='left', rsuffix=f'_{a}')
df_all = df_all.dropna()
for a in Coinlist[1:] :
    for mode in ['high','low','close']:
        df_all[f'{mode}_{a}'] = df_all[f'{mode}_{a}']/df_all[f'{mode}']
for mode in ['high','low','close']:
    df_all[f'{mode}'] = df_all[f'{mode}']/df_all[f'{mode}']
df_all = df_all.pct_change(1)
df_all = df_all +1
df_all = df_all.dropna()
df_all.to_parquet('./data/df_all.parquet')

In [65]:
df_all

,high,low,close,high_ADA,low_ADA,close_ADA,high_DOGE,low_DOGE,close_DOGE,high_ETH,...,close_ETH,high_LINK,low_LINK,close_LINK,high_LTC,low_LTC,close_LTC,high_XRP,low_XRP,close_XRP
date,,,,,,,,,,,,,,,,,,,,,
2019-07-08 02:00:00,1.0,1.0,1.0,1.015760,1.008899,1.013568,0.996544,0.991976,0.990525,0.999111,...,1.002386,0.997384,1.004148,1.019467,1.006480,0.998962,0.992521,1.003626,0.999997,0.994763
2019-07-08 06:00:00,1.0,1.0,1.0,1.014056,1.012068,1.005437,0.985195,0.977443,0.988965,1.004303,...,1.003410,1.066802,1.009831,1.027672,0.990998,0.993855,0.999162,0.996807,0.993752,0.998126
2019-07-08 10:00:00,1.0,1.0,1.0,0.961412,0.986278,0.943467,0.972935,1.005011,0.982780,0.964375,...,0.958652,0.937447,1.010517,0.943119,0.974168,0.999931,0.973108,0.965836,0.998288,0.963647
2019-07-08 14:00:00,1.0,1.0,1.0,0.985111,0.965283,1.003511,1.002066,0.948310,0.982204,0.997815,...,1.008877,0.976360,0.952192,0.999447,1.000351,0.967318,1.001134,1.013652,0.967884,1.010971
2019-07-08 18:00:00,1.0,1.0,1.0,0.962945,0.993855,0.962519,0.961607,1.012790,0.980700,0.974039,...,0.976873,0.960974,0.997663,0.960609,0.974073,1.006666,0.974581,0.962984,1.005597,0.973600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-05 21:00:00,1.0,1.0,1.0,0.989221,0.999461,0.986223,0.993309,1.002528,0.995342,1.011427,...,1.012510,0.999176,1.003094,0.993839,0.986399,0.990311,0.985000,0.987435,1.012626,0.984538
2025-02-06 01:00:00,1.0,1.0,1.0,1.002232,1.005378,1.015525,1.001484,1.003388,1.006970,1.008113,...,0.998845,1.002720,1.001300,1.008406,1.002306,1.010488,1.011749,0.990919,1.003876,1.010579
2025-02-06 05:00:00,1.0,1.0,1.0,1.007635,1.014535,1.005056,1.011473,1.008971,1.003683,1.003273,...,1.000223,1.008108,1.012857,1.000995,1.013405,1.010507,1.007337,1.003619,1.007024,0.997789
2025-02-06 09:00:00,1.0,1.0,1.0,0.992799,0.993585,0.987316,0.989974,0.994646,0.991190,0.993575,...,0.983460,0.992062,0.994884,0.994936,1.003809,1.004182,0.990684,0.993912,0.996016,0.996615
2025-02-06 13:00:00,1.0,1.0,1.0,0.989323,0.983692,0.993084,0.993910,0.991399,0.997585,0.983367,...,0.997648,0.992760,0.989671,0.996679,0.977780,0.987768,1.001114,0.993967,0.985347,0.993598

In [66]:
df_all = pd.read_parquet('./data/df_all.parquet')
df = df_all

In [67]:
df

,high,low,close,high_ADA,low_ADA,close_ADA,high_DOGE,low_DOGE,close_DOGE,high_ETH,...,close_ETH,high_LINK,low_LINK,close_LINK,high_LTC,low_LTC,close_LTC,high_XRP,low_XRP,close_XRP
date,,,,,,,,,,,,,,,,,,,,,
2019-07-08 02:00:00,1.0,1.0,1.0,1.015760,1.008899,1.013568,0.996544,0.991976,0.990525,0.999111,...,1.002386,0.997384,1.004148,1.019467,1.006480,0.998962,0.992521,1.003626,0.999997,0.994763
2019-07-08 06:00:00,1.0,1.0,1.0,1.014056,1.012068,1.005437,0.985195,0.977443,0.988965,1.004303,...,1.003410,1.066802,1.009831,1.027672,0.990998,0.993855,0.999162,0.996807,0.993752,0.998126
2019-07-08 10:00:00,1.0,1.0,1.0,0.961412,0.986278,0.943467,0.972935,1.005011,0.982780,0.964375,...,0.958652,0.937447,1.010517,0.943119,0.974168,0.999931,0.973108,0.965836,0.998288,0.963647
2019-07-08 14:00:00,1.0,1.0,1.0,0.985111,0.965283,1.003511,1.002066,0.948310,0.982204,0.997815,...,1.008877,0.976360,0.952192,0.999447,1.000351,0.967318,1.001134,1.013652,0.967884,1.010971
2019-07-08 18:00:00,1.0,1.0,1.0,0.962945,0.993855,0.962519,0.961607,1.012790,0.980700,0.974039,...,0.976873,0.960974,0.997663,0.960609,0.974073,1.006666,0.974581,0.962984,1.005597,0.973600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-05 21:00:00,1.0,1.0,1.0,0.989221,0.999461,0.986223,0.993309,1.002528,0.995342,1.011427,...,1.012510,0.999176,1.003094,0.993839,0.986399,0.990311,0.985000,0.987435,1.012626,0.984538
2025-02-06 01:00:00,1.0,1.0,1.0,1.002232,1.005378,1.015525,1.001484,1.003388,1.006970,1.008113,...,0.998845,1.002720,1.001300,1.008406,1.002306,1.010488,1.011749,0.990919,1.003876,1.010579
2025-02-06 05:00:00,1.0,1.0,1.0,1.007635,1.014535,1.005056,1.011473,1.008971,1.003683,1.003273,...,1.000223,1.008108,1.012857,1.000995,1.013405,1.010507,1.007337,1.003619,1.007024,0.997789
2025-02-06 09:00:00,1.0,1.0,1.0,0.992799,0.993585,0.987316,0.989974,0.994646,0.991190,0.993575,...,0.983460,0.992062,0.994884,0.994936,1.003809,1.004182,0.990684,0.993912,0.996016,0.996615
2025-02-06 13:00:00,1.0,1.0,1.0,0.989323,0.983692,0.993084,0.993910,0.991399,0.997585,0.983367,...,0.997648,0.992760,0.989671,0.996679,0.977780,0.987768,1.001114,0.993967,0.985347,0.993598

In [228]:
class Data_portfolio(Dataset):
    def __init__(self, flag, input_len):
        super().__init__()
        self.flag = flag
        self.input_len = input_len
        self.__read_data__()

    def __read_data__(self):
        df_all = pd.read_parquet('./data/df_all.parquet')
        self.split = int(0.7 * df_all.shape[0])
        if self.flag == 'train':
            self.data = df_all[:self.split]
            self.data = np.array(self.data)
        elif self.flag == 'test':
            self.data = df_all[self.split:]
    def __getitem__(self, index):  
        seq_x =self.data[index:index+self.input_len]
        seq_y = self.data[index+self.input_len:index+self.input_len+1,2::3]
        seq_x = torch.tensor(seq_x)
        seq_y = torch.tensor(seq_y)
        return seq_x, seq_y
    
    def __len__(self):
        return self.data.shape[0]-self.input_len

In [229]:
dataset = Data_portfolio('train', 25)

In [230]:
data_loader = DataLoader(dataset, batch_size= 60, shuffle = True)

In [231]:
x, y = next(iter(data_loader))

In [232]:
x.shape

torch.Size([60, 25, 21])

In [233]:
import torch.nn as nn
class ResBlock(nn.Module):
    def __init__(self, seq_len, pred_len, d_model, dropout, enc_in):
        super(ResBlock, self).__init__()

        self.temporal = nn.Sequential(
            nn.Linear(seq_len, d_model),
            nn.ReLU(),
            nn.Linear(d_model, seq_len),
            nn.Dropout(dropout)
        )

        self.channel = nn.Sequential(
            nn.Linear(enc_in, d_model),
            nn.ReLU(),
            nn.Linear(d_model, enc_in),
            nn.Dropout(dropout)
        )

    def forward(self, x):
        # x: [B, L, D]
        x = x + self.temporal(x.transpose(1, 2)).transpose(1, 2)
        x = x + self.channel(x)
        return x


class Model(nn.Module):
    def __init__(self, seq_len, pred_len, d_model, dropout, enc_in, method, batch_size, revin = False):
        super(Model, self).__init__()
        self.layer = 3
        self.model = nn.ModuleList([ResBlock(seq_len, pred_len, d_model, dropout, enc_in)
                                    for _ in range(3)])
        # self.M = torch.tensor(pkl.load(open('projection_mat.pkl', 'rb'))).unsqueeze(0).repeat(batch_size,1,1).float()
        self.pred_len = pred_len
        self.seq_len = seq_len
        self.method = method

        self.projection = nn.Linear(self.seq_len, self.pred_len)
        self.projection2 = nn.Linear(enc_in, 7)
        self.last_activ = nn.Softmax(dim =1)
        self.revin = revin

    def forecast(self, x_enc):
 
        for i in range(self.layer):
           x_enc = self.model[i](x_enc)
        
        enc_out = self.projection(x_enc.transpose(1, 2)).transpose(1, 2)
        enc_out = self.projection2(enc_out)
        return enc_out

    def forward(self, x_enc):
        dec_out = self.forecast(x_enc).squeeze()
        dec_out = self.last_activ(dec_out)
        return dec_out

In [234]:
model = Model(seq_len=25,pred_len=1,d_model = 512, dropout = 0.1, enc_in = 21, method='None', batch_size=60, revin = False)

In [235]:
y = y.squeeze()

In [236]:
out = model(x.float())

In [237]:
out_opti = torch.zeros_like(y)
for i,a in enumerate(torch.argmax(y, dim = 1)):
    out_opti[i,a] = 1

In [238]:
1/60* torch.sum(torch.log(torch.sum(out*y, dim = 1)))

tensor(-0.0004, dtype=torch.float64, grad_fn=<MulBackward0>)

In [239]:
1/60 * torch.sum(torch.log(torch.sum(out_opti*y, dim = 1)))

tensor(0.0132, dtype=torch.float64)

In [ ]:
model.train()
model_optim = optim.Adam(model.parameters(), lr=0.001, maximize = True)
for batch in data_loader :
    batch_x, batch_y = batch
    model_optim.zero_grad()

In [24]:
x = df[100:180]

In [26]:
X = [] ; Y = []
for i in range(60):
    X.append(x[i:i+20].values)
    Y.append(x[i+20:i+20+1])

X = np.array(X)
Y = np.array(Y)

In [27]:
X[0,:,5]

array([5.94457902e-06, 5.92783811e-06, 5.99453949e-06, 5.96081166e-06,
       5.90348114e-06, 5.86235228e-06, 5.97352763e-06, 5.94293757e-06,
       5.92477131e-06, 5.92256947e-06, 6.09650293e-06, 6.41412593e-06,
       6.27587599e-06, 6.31880545e-06, 6.36814485e-06, 6.23227632e-06,
       6.20866008e-06, 6.15285474e-06, 6.17954514e-06, 6.17155628e-06])

In [31]:
X

array([[[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.21085964e-05, 3.18512850e-05, 3.20624987e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.20466703e-05, 3.25196100e-05, 3.24601660e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.22982521e-05, 3.26347625e-05, 3.23125190e-05],
        ...,
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.17205251e-05, 3.24645093e-05, 3.24982143e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.26759985e-05, 3.27400884e-05, 3.27697757e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.28162389e-05, 3.27891102e-05, 3.27999084e-05]],

       [[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.20466703e-05, 3.25196100e-05, 3.24601660e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.22982521e-05, 3.26347625e-05, 3.23125190e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.17568255e-05, 3.23819358e-05, 3.15724451e-05],
        ...,
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.26759985e-05, 3.27400884e-05, 3.27697757e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.28162389e-05, 3.27891102e-05, 3.27999084e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.27140558e-05, 3.30140997e-05, 3.26553432e-05]],

       [[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.22982521e-05, 3.26347625e-05, 3.23125190e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.17568255e-05, 3.23819358e-05, 3.15724451e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.15721290e-05, 3.15818581e-05, 3.15377368e-05],
        ...,
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.28162389e-05, 3.27891102e-05, 3.27999084e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.27140558e-05, 3.30140997e-05, 3.26553432e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         3.27036956e-05, 3.28701051e-05, 3.26931749e-05]],

       ...,

       [[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.91455646e-05, 2.96158987e-05, 2.91418678e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.90353309e-05, 2.91497166e-05, 2.90621088e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.89901244e-05, 2.92710203e-05, 2.93070955e-05],
        ...,
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.73857254e-05, 2.74150028e-05, 2.72477162e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.72379660e-05, 2.74277280e-05, 2.72849741e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.62809392e-05, 2.73031054e-05, 2.64260144e-05]],

       [[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.90353309e-05, 2.91497166e-05, 2.90621088e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.89901244e-05, 2.92710203e-05, 2.93070955e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.93223149e-05, 2.94636850e-05, 2.93763816e-05],
        ...,
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.72379660e-05, 2.74277280e-05, 2.72849741e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.62809392e-05, 2.73031054e-05, 2.64260144e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.63651802e-05, 2.70689613e-05, 2.68666230e-05]],

       [[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.89901244e-05, 2.92710203e-05, 2.93070955e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.93223149e-05, 2.94636850e-05, 2.93763816e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.91111829e-05, 2.93890676e-05, 2.91245829e-05],
        ...,
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.62809392e-05, 2.73031054e-05, 2.64260144e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.63651802e-05, 2.70689613e-05, 2.68666230e-05],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         2.68453482e-05, 2.71489367e-05, 2.68918056e-05]]])

In [29]:
batch_size = 50
train_set = df_all[:1000]

In [37]:
class ReplayBuffer:
    def __init__(self, start_index, end_index, batch_size, is_permed, coin_number, sample_bias=1.0):
        """
        :param start_index: start index of the training set on the global data matrices
        :param end_index: end index of the training set on the global data matrices
        """
        self.__coin_number = coin_number
        self.__experiences = [Experience(i) for i in range(start_index, end_index)]
        self.__is_permed = is_permed
        # NOTE: in order to achieve the previous w feature
        self.__batch_size = batch_size
        self.__sample_bias = sample_bias

    def append_experience(self, state_index):
        self.__experiences.append(Experience(state_index))

    def __sample(self, start, end, bias):
        """
        @:param end: is excluded
        @:param bias: value in (0, 1)
        """
        # TODO: deal with the case when bias is 0
        ran = np.random.geometric(bias)
        while ran > end - start:
            ran = np.random.geometric(bias)
        result = end - ran
        return result

    def next_experience_batch(self):
        # First get a start point randomly
        batch = []
        if self.__is_permed:
            for i in range(self.__batch_size):
                batch.append(self.__experiences[self.__sample(self.__experiences[0].state_index,
                                                              self.__experiences[-1].state_index,
                                                              self.__sample_bias)])
        else:
            batch_start = self.__sample(0, len(self.__experiences) - self.__batch_size,
                                        self.__sample_bias)
            batch = self.__experiences[batch_start:batch_start+self.__batch_size]
        return batch


class Experience:
    def __init__(self, state_index):
        self.state_index = int(state_index)

In [39]:
rp = ReplayBuffer(0,100, 5, True, 10)

In [42]:
rp.next_experience_batch()

[<__main__.Experience at 0x299fb8dd0>,
 <__main__.Experience at 0x299fb8dd0>,
 <__main__.Experience at 0x299fb8dd0>,
 <__main__.Experience at 0x299fb8dd0>,
 <__main__.Experience at 0x299fb8dd0>]

In [44]:
def __pack_samples(self, indexs):
        indexs = np.array(indexs)
        last_w = self.__PVM.values[indexs-1, :]

        def setw(w):
            self.__PVM.iloc[indexs, :] = w
        M = [self.get_submatrix(index) for index in indexs]
        M = np.array(M)
        X = M[:, :, :, :-1]
        y = M[:, :, :, -1] / M[:, 0, None, :, -2]
        return {"X": X, "y": y, "last_w": last_w, "setw": setw}

    # volume in y is the volume in next access period
def get_submatrix(self, ind):
    return self.__global_data.values[:, :, ind:ind+self._window_size+1]

In [55]:
train_set = df_all.iloc[:100,4:].values.reshape((100,6,4))

In [54]:
df_all.iloc[:100,4:].values.reshape((100,6,4))

array([[[6.89032285e-06, 6.92897524e-06, 6.95436900e-06, 6.98149106e-06],
        [3.08723727e-07, 3.11639405e-07, 3.12361160e-07, 3.09892358e-07],
        [2.67076648e-02, 2.68253295e-02, 2.68345289e-02, 2.67222069e-02],
        [2.92486108e-04, 2.93035747e-04, 2.88286980e-04, 2.86880593e-04],
        [1.03725012e-02, 1.04142949e-02, 1.05043247e-02, 1.04784077e-02],
        [3.43398481e-05, 3.45235851e-05, 3.48477601e-05, 3.47687008e-05]],

       [[6.98622724e-06, 7.03817891e-06, 7.01625406e-06, 7.07621492e-06],
        [3.09878068e-07, 3.10562260e-07, 3.09854875e-07, 3.06956038e-07],
        [2.67066717e-02, 2.68014840e-02, 2.67930597e-02, 2.67859772e-02],
        [2.86859255e-04, 2.92269273e-04, 2.89482807e-04, 2.92465345e-04],
        [1.04759175e-02, 1.04817770e-02, 1.04934215e-02, 1.04000401e-02],
        [3.47419248e-05, 3.46487842e-05, 3.48476533e-05, 3.45866254e-05]],

       [[7.07562358e-06, 7.13710551e-06, 7.10092702e-06, 7.11468747e-06],
        [3.06930386e-07, 3.05964458e-07, 3.02865631e-07, 3.03568750e-07],
        [2.67880569e-02, 2.69168235e-02, 2.67330641e-02, 2.68773140e-02],
        [2.92432096e-04, 3.11793516e-04, 2.92328715e-04, 3.00558353e-04],
        [1.03981409e-02, 1.03874157e-02, 1.04289436e-02, 1.03913292e-02],
        [3.46240317e-05, 3.45381520e-05, 3.46299144e-05, 3.45218163e-05]],

       ...,

       [[5.64130430e-06, 5.65175547e-06, 5.60276063e-06, 5.64843354e-06],
        [2.85918704e-07, 2.86276565e-07, 2.89866130e-07, 2.88805961e-07],
        [2.15442518e-02, 2.15383437e-02, 2.09911983e-02, 2.11948411e-02],
        [2.38906144e-04, 2.38747906e-04, 2.36179510e-04, 2.41048197e-04],
        [9.13038717e-03, 9.12969191e-03, 9.03237573e-03, 9.16920455e-03],
        [3.13103947e-05, 3.13075684e-05, 3.14760640e-05, 3.17111894e-05]],

       [[5.64234608e-06, 5.69463340e-06, 5.63702096e-06, 5.69739868e-06],
        [2.88865728e-07, 2.88239679e-07, 2.89027714e-07, 2.87846879e-07],
        [2.11938562e-02, 2.12009995e-02, 2.11341671e-02, 2.12296965e-02],
        [2.40714529e-04, 2.47923147e-04, 2.40606080e-04, 2.45180769e-04],
        [9.17108049e-03, 9.19378793e-03, 9.18427850e-03, 9.19321814e-03],
        [3.17008235e-05, 3.14697560e-05, 3.17384877e-05, 3.15748697e-05]],

       [[5.69645280e-06, 5.72798712e-06, 5.74037952e-06, 5.75276980e-06],
        [2.87345928e-07, 2.89472661e-07, 2.89493995e-07, 2.87576765e-07],
        [2.12299082e-02, 2.13103612e-02, 2.13464369e-02, 2.13375102e-02],
        [2.45140064e-04, 2.47283637e-04, 2.40534381e-04, 2.41283017e-04],
        [9.18729172e-03, 9.26315030e-03, 9.23434394e-03, 9.26316607e-03],
        [3.15653637e-05, 3.17410928e-05, 3.17969635e-05, 3.17057255e-05]]])

In [67]:
train_set = torch.tensor(train_set).permute(1,2,0)

In [74]:
train_set.shape

torch.Size([6, 4, 100])

In [82]:
window_size = 10

In [92]:
def __pack_samples(x, indexs):
    M = [get_submatrix(x, index) for index in indexs]
    M = np.array(M)
    X = M[:, :, :, :-1]
    y = M[:, :, :, -1] / M[:, 0, None, :, -2]
    return {"X": X, "y": y}

# volume in y is the volume in next access period
def get_submatrix(X, ind):
    return X[:, :, ind:ind+window_size+1]

In [95]:
dic = __pack_samples(train_set, [10, 15, 50])